### ISSUE TITLE
Update to 9.20

### ISSUE THREAD

**Issue by marty-cz** [OpenIxia/BreakingPoint#14]
Hi OpenIxia team,

do you plan to update BPS Python lib to version 9.20.115.12? Or do you have any BPS API Changelogs which could be used to update this lib on our own?

Thank you,
Martin

**Comment by nutu** [comment]
Hi Marty,
We are a little bit behind with publishing it on github it will be made available  in the next couple of weeks. Although if you need it earlier you can download it from the BPS UI application.
![image](https://user-images.githubusercontent.com/2760554/180074964-0e1793d2-7c3f-4673-bd73-7f69e1ac1b92.png)

Would that work for you?

Regards,
C

**Comment by marty-cz** [comment]
Hi nutu,

yes, it will work ;) There was a bug in 9.10 which has older Python lib inside. After update to 9.22 it is fixed.

However my question to API Changelog still remains. Maybe you can just publish OpenAPI spec (like Network Packer broker does) so it would be quite simple to diff two files to see changes ;)

Thank you,
Martin

**Comment by nutu** [comment]
we are planning to get back on pypi repository soon. For now please use either the version that can be downloaded from BreakingPoint server or directly from the github repository.
