### ISSUE TITLE
Missing API endpoint for exporting network neighborhood BPT files.

### ISSUE THREAD

**Issue by eephillip** [OpenIxia/BreakingPoint#9]
Reviewing both v1/v2 api documentation and code. There doesn't to be a way to export Network neighborhood BPT files via either API version.

BPSv1
In version 1, you could retrieve and then view a json representation via the following
```
v1/bps/network/operations/retrieve
v1/bps/network/
```

BPSv2 network operations has save load and new operations but no BPT export for networks.
```
  289:     def _network_operations_search(self, searchString, userid, clazz, sortorder, sort, limit, offset):
  526:     def _network_operations_importNetwork(self, name, filename, force):
  546:     def _network_operations_saveAs(self, name, regenerateOldStyle=True, force=False):
  557:     def _network_operations_save(self, name=None, regenerateOldStyle=True, force=True):
  730:     def _network_operations_delete(self, name):
 1054:     def _network_operations_list(self, userid, clazz, sortorder, sort, limit, offset):
 1138:     def _network_operations_load(self, template):
 1147:     def _network_operations_new(self, template=None):
 ```

**Comment by nutu** [comment]
Hi Phillip, 
You are right.  The export Network neighborhood was not yet added. It will come in a future release.
There is a simple workaround  to  it though to  save the network neighborhood  in a test configuration and export that.
On import of the testModel you will also get the network neighborhood that was saved in it.
In most of the use cases we seen that this is actually the flow that the users are anyway taking.

#set the network in a testmodel as in s04_Configure_Network.py
.....
print ("Saving network as : %s" % new_network_name)
bps.network.saveAs(new_network_name, force=True)

print ('Assigning the network in a existing testmodel')
bps.testmodel.load('AppSim')
bps.testmodel.network.set(new_network_name)
print ('Saving  testmodel as : %s' % new_testmodel_name)
bps.testmodel.saveAs(new_testmodel_name,force= True)
#..................
#use any of the examples to to a short run with the nn and obtain the runid (or get it from the results)
print("Run test and Get Stats:")
test_id_json = bps.testmodel.run(modelname=new_testmodel_name, group=2)
the_run_id = test_id_json["runid"]

#.............................
bps.testmodel.exportModel(name ='new_testmodel_name' , attachments = False, filepath = 'exported_for_network', runid = the_run_id )

Regards,
C

**Comment by eephillip** [comment]
Ahh! Never noticed that the network was embedded, that sounds good to me.
I'm finding that performing a test to get the run id unnecessary. I create a dummy test model and attach the network, then just export by name. 
Then remove the testmodel tree from the xml, and delete the model

```
from defusedxml.ElementTree import parse as xmlparse

def export():
    bps = BPSv2(ixia['hostname'],
                ixia['user'],
                ixia['password'])
    bps.login()

    temp_model='tmp-model'
    temp_file=os.path.join(tempfile.gettempdir(), temp_model)
    networks = bps.network.search(searchString='test',
                                  userid='',
                                  clazz='',
                                  sortorder='ascending',
                                  sort='name',
                                  limit='',
                                  offset=0)
   
    for net in networks:
        network_file = os.path.join(os.path.getcwd(), net['name'] + '.bpt')
        bps.testmodel.new()
        bps.testmodel.network.set(net['name'])
        bps.testmodel.saveAs(temp_model, force=True)

        bps.testmodel.exportModel(name=temp_model,
                                  attachments=True,
                                  filepath=temp_file)

        xml=xmlparse(temp_file)
        root = xml.getroot()

        for el in root.findall('testmodel'):
            root.remove(el)
            
        xml.write(nn_file)

    bps.testmodel.delete(temp_model)
    bps.logout()
```
